name: Manual Workflow Trigger with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'image to deploy'
        required: true
        default: 'no'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to environment
      run: | 
        ls
        git submodule add https://github.com/shamablyat/ci-cd.git ci-cd
        cd ci-cd
        echo 
        pwd
        ls
        echo 
        rm -rf ci-cd
        echo
